name: Simple RP Pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: echo "This is the simple job step."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          ls -la
          uname -a
          ps
          ip a
