name: Simple RP Pipeline
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the simple job step."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy Microservice
        run: $SHELL deploy-microservice.sh
      - name: Test Microservice Deploy
        run: curl localhost
